import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";

const exoFont = Exo_2({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beats by E. Hannah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning={true}
      className={`${exoFont.variable} antialiased`}
    >
      <body className='font-main'>{children}</body>
    </html>
  );
}
